### PR TITLE
New article post for review

### PR DESCRIPTION
**Pull request by AreRex14**
@IceM4nn I have write a new post for review, can you check on it...I have set the date to be post on 6/7.

!Please change the published to true before you approve the request

### CODE REVIEW

**Comment by kaitoAckerman** [comment]
Hey, I think I just messed up. your post doesnt show up. you set `published: false` may I know why ?

**Comment by AreRex14** [comment]
Because maybe you may not view this PR at this time so I set the post to be live on 6/7..so you have time to review the PR, will the published set to true make the article directly post today or will it still be publish on the date that had been set..?

⁣Sent from BlueMail ​

**Comment by kaitoAckerman** [comment]
Oh yea I see, and also, yep. if you set `published:true` or do not put any `published` option. which is also return as true by default. The post will only show on date we set. 

For you case, even I remove `published` option. the post still wont show up. until the date equal to date today. So do you want me to remove `published:false` for you?. Still the post will only show up on the date you set.

**Comment by kaitoAckerman** [comment]
Okay, everything perfect now. your post will be available on 6 july.

**Comment by AreRex14** [comment]
Roger that

⁣Sent from BlueMail ​

**Pull request merged**
