### PR TITLE
Another write-up unikl CTF

### PR DESCRIPTION
**Pull request by fareedfauzi**

### CODE REVIEW

**Comment by kaitoAckerman** [comment]
There is to much confict

**Comment by kaitoAckerman** [comment]
@fareedfauzi ? Aku rasa kau tk sync dgn latest commit branch master sig. 

Dah bt step 2 mcm dlm [gist](https://gist.github.com/CristinaSolana/1885435) ni ?
lepas tu run `git pull upstream master`

**Comment by kaitoAckerman** [comment]
@fareedfauzi ? still available?
run command below to make sure you already get latest code from our repo. 

```
# check if upstream repo already added
git remote -v

#if not (if you are using ssh)
git remote add upstream git@github.com:SiG-FSTM/sig-fstm.github.io.git

#(if you are using https)
git remote add upstream https://github.com/SiG-FSTM/sig-fstm.github.io.git

#get latest commit from original repo
git fetch upstream

# make sure you already in master branch
git checkout master

#merge dev branch from original repo into your dev repo
git merge upstream/master

# push your latest code into github
git push
```

**Comment by kaitoAckerman** [comment]
@fareedfauzi ? Dah lama sngt PR ni. I will close it. Since there is no respond from you. Boleh bt PR baru, tpi kena ingt. Sblum bt PR.

Make sure code dlm repo kau, sama latest dgn repo ni.

**Comment by fareedfauzi** [comment]
alamak. Ok baik2

On Tue, Jun 19, 2018 at 6:44 PM, norFarhan norizam <notifications@github.com

**Comment by kaitoAckerman** [comment]
@fareedfauzi ? kau boleh reopen balik PR ni . tpi make sure repo kau ada latest update dgn repo ni.

**Comment by fareedfauzi** [comment]
okay baik in shaa Allah

On Mon, Jun 25, 2018 at 6:49 PM, norFarhan norizam <notifications@github.com

**Pull request closed without merging**
